gesdinet_jwt_refresh_token:
    ttl: 2592000
    single_use: true
    cookie:
        enabled: true
        # same_site: lax               # default value
        # path: /                      # default value
        # domain: null                 # default value
        # http_only: true              # default value
        secure: false                 # default true !!!
        # remove_token_from_body: true # default value
